// Generated by CoffeeScript 1.4.0
(function() {
  var test, test1;

  test = (function() {

    function test(name) {
      this.name = name;
      console.log(this.name);
    }

    test.prototype.name = function() {
      return console.log(this.name);
    };

    test.display = function() {
      return console.log("this is a test");
    };

    return test;

  })();

  test1 = new test;

  test.name();

  test.display();

}).call(this);
