// Generated by CoffeeScript 1.4.0
var value;

$("#year").focusout(function() {
  if ($(this).val() <= 4) {
    return $("#month").focus();
  } else {
    return $("#last_name").focus();
  }
});

value = $("#age").val() + "y" + $("#month").val() + "m";

$("age").val(value);
