// Generated by CoffeeScript 1.4.0
(function() {
  var Medium, Podcast, Screencast, podcast, screencast,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Medium = (function() {

    function Medium(name) {
      this.name = name;
    }

    Medium.prototype.download = function(episode) {
      return console.log('Downloading ' + episode + ' of ' + this.name);
    };

    Medium.play = function(episode, name) {
      return console.log('Playing ' + episode + ' of ' + name);
    };

    Medium.prototype.playOn = function() {
      return console.log('unknown');
    };

    return Medium;

  })();

  Podcast = (function(_super) {

    __extends(Podcast, _super);

    function Podcast(name, description) {
      this.description = description;
      Podcast.__super__.constructor.call(this, name);
    }

    Podcast.prototype.listen = function() {
      return console.log('Listening to ' + this.name);
    };

    Podcast.prototype.playOn = function() {
      return console.log('iPod');
    };

    return Podcast;

  })(Medium);

  Screencast = (function(_super) {

    __extends(Screencast, _super);

    function Screencast(name, description, author) {
      this.description = description;
      this.author = author;
      Screencast.__super__.constructor.call(this, name);
    }

    Screencast.prototype.watch = function() {
      return console.log('Watching ' + this.name);
    };

    Screencast.prototype.playOn = function() {
      return console.log('iPad');
    };

    return Screencast;

  })(Medium);

  podcast = new Podcast('Astronomy Cast', 'A fact-based journey through the galaxy.');

  podcast.download('the first episode');

  podcast.listen();

  screencast = new Screencast('RailsCasts', 'Ruby on Rails Screencasts', 'Ryan Bates');

  screencast.download('the 267th episode');

  screencast.watch();

}).call(this);
