// Generated by CoffeeScript 1.4.0
var inputManager;

inputManager = (function() {

  function inputManager() {
    this.debug = false;
    this.previous_selected_field = null;
    this.initializeForm();
    this.isAutocompleteSelected = false;
    this.checkCookie();
    this.previousImageUrl = "";
    this.nextImageUrl = "";
  }

  inputManager.prototype.initializeForm = function() {
    this.bindEvents();
    this.bindKbdEvents();
    return this.collapsibleInstructions();
  };

  $('a[rel*=facebox]').facebox();

  $("#previous_image").hide();

  inputManager.prototype.bindEvents = function() {
    $("#first_name").focus(function() {
      $('.ui-autocomplete').hide();
      $(this).autocomplete(autocomplete_first_name);
      return this.isAutoCompleteSelected = false;
    });
    $("#last_name").focus(function() {
      $('.ui-autocomplete').hide();
      $(this).autocomplete(autocomplete_last_name);
      return this.isAutoCompleteSelected = false;
    });
    $("#middle_name").focusout(function() {
      return $(this).val($(this).val().capitalize());
    });
    $("#submit_btn").click(function() {
      if ($("h3.btn-showhide").hasClass("open")) {
        $(".btn-showhide>a").click();
      }
      return this.submit_values();
    });
    $(".name").focusout(function() {
      if ($(this).val().trim() === "-" && ($(this).is("#last_name"))) {
        $(this).val("<SAMEASPREVIOUS>");
      }
      return $(this).val($(this).val().trim().capitalize());
    });
    $('#last_name').keypress(function(e) {
      return this.inputLimiter(e, "NameCharacters");
    });
    $('#age').keypress(function(e) {
      return this.inputLimiter(e, "NumbersSymbols");
    });
    $('#middle_name,  #first_name').keypress(function(e) {
      return this.inputLimiter(e, "Letters");
    });
    $("#age").focus();
    $("#age_tip").tipTip({
      activation: "hover",
      maxWidth: 700,
      defaultPosition: "bottom",
      fadeIn: 100,
      content: "<ul class='age_tooltip'><li>Age may be written as a whole number (e.g.: 5) or as a fraction (e.g.: 6 1/12).</li><li>The fraction denotes the months (e.g.: 6 1/12 means 6 years 5 months)</li><li> Capture the months only if the age is less than 1.</li><li>Examples:  2 1/12 => 2   And  5/12 => 5m</li></ul>"
    });
    $("#btn_unreadable").click(function() {
      return this.skip_task();
    });
    $("#btn_noname").click(function() {
      return this.flag_task();
    });
    $("#show_pvs_image").click(function() {
      return this.show_prev_next_image();
    });
    $("#last_name, #first_name").focusout(function() {
      if ($("#age").val()) {
        return this.validate_name_by_age($(this).val());
      }
    });
    return $(".btn-showhide>a").live(function() {
      return click(function() {
        var string, _ref;
        string = (_ref = $(this).html() === "↑ Quick Help") != null ? _ref : {
          "↓ Quick Help": "↑ Quick Help"
        };
        return $(this).html(string);
      });
    });
  };

  inputManager.prototype.submitValues = function() {
    if (this.validate()) {
      return $("#cf_task_form").submit();
    } else {
      self.focus_empty_input();
      return false;
    }
  };

  inputManager.prototype.validate = function() {
    var validated;
    validated = true;
    if ($("#last_name").val() === "" || $("#first_name").val() === "") {
      validated = false;
    }
    if ($("#age").val() === "" || $("#age").val() < 0 || $("#age").val() >= 150) {
      validated = false;
    }
    return validated;
  };

  return inputManager;

})();


    input_manager.prototype.bind_kbd_shortcuts = function()
    {
        var self = this;
        var isCtrl = false,
            isShift = false,
            numeric_key_codes = [49, 50, 51];

        $(document).keyup(function(e)
        {
            if (e.which === 16) isShift = false;
            if (e.which === 17) isCtrl = false;
        }).keydown(function(e)
        {
            if (e.which === 16) isShift = true;
            if (e.which === 17) isCtrl = true;

            if (e.which === 13 && isCtrl && !isShift)
            { // Ctrl + Enter for skipping the task
                self.skip_task();
            }

            else if (e.which === 13 && !isCtrl && isShift)
            { // Shift + Enter for flagging the task
                self.flag_task();
            }

            else if (e.which === 13 && !isCtrl && !isShift && self.isAutoCompleteSelected == false)
            { // Enter to submit the task
                self.submit_values();
            }

            else if ((e.which === 112 || e.which === 80) && isCtrl && isShift)
            { // shortcut to view previous image Ctrl + Shift + P
                $("#show_pvs_image").click();
            }
        });
    };



;

